### ISSUE TITLE
crun: change crun to run in rootless mode without needing to disable selinux

### ISSUE THREAD

**Issue by msterin** [kontainapp/km#941]
Note: Open /dev/kvm is needed and process tag does not match /dev/kvm tag. Crun will need the related capability (or set proper tags on crun)

**Comment by paulpopelka** [comment]
The problem here was /opt/kontain/bin/km did not have the correct security context to allow it to open /dev/kvm while running within a selinux policy.
We made some changes in the script that installs km to set its security context and then things worked.
Look in the file: ./container-runtime/podman_config.sh

This was fixed with this github km repository PR:
```
commit 947175fe8fd28da83bd112a58478d0da3ef8147a
Author: paulpopelka <paulp@kontain.app>
Date:   Mon Aug 30 11:08:50 2021 -0700

    Changes to support make validate-*-image targets using podman (#1322)
```
